language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
install: npm install
after_success: npm test-cov
deploy:
  app: 
    master: koi-api
    develop: staging-koi-api
  provider: heroku
  api_key:
    secure: OEjbn8Z4ZHKqQ13v8MMClDRarF8WD+sQXyFXyuEdFLE1HwvrZJNClVZobOxAeoXDUoX38J0xujXjeZGtkOXaVsQz5tRK1RXZcXJMONfsD//sol9+X8DuTJLw5BDCBobX/C8kYHvAXf0Sp2zSyNECYYQ/Hshakr8MezNXtitKh/c=
  node: 0.12
