language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install: 
- npm install -g grunt-cli 
- npm install -g bower
install: npm install
before_script: 
- grunt build
- bower install
deploy:
  app: koi-api
  provider: heroku
  api_key:
    secure: OEjbn8Z4ZHKqQ13v8MMClDRarF8WD+sQXyFXyuEdFLE1HwvrZJNClVZobOxAeoXDUoX38J0xujXjeZGtkOXaVsQz5tRK1RXZcXJMONfsD//sol9+X8DuTJLw5BDCBobX/C8kYHvAXf0Sp2zSyNECYYQ/Hshakr8MezNXtitKh/c=
  node: 0.12
